EEEE
======================================================================
ERROR: test_generate_table_data (tests.TestOutput.test_generate_table_data)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dft/Dev/selfhealing-code/selfheal-py-2/tests.py", line 57, in test_generate_table_data
    parsed_data = parse_yaml_data(self.yaml_data)
                  ^^^^^^^^^^^^^^^
NameError: name 'parse_yaml_data' is not defined

======================================================================
ERROR: test_generate_table_headers (tests.TestOutput.test_generate_table_headers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dft/Dev/selfhealing-code/selfheal-py-2/tests.py", line 52, in test_generate_table_headers
    parsed_data = parse_yaml_data(self.yaml_data)
                  ^^^^^^^^^^^^^^^
NameError: name 'parse_yaml_data' is not defined

======================================================================
ERROR: test_organize_table_data (tests.TestOutput.test_organize_table_data)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dft/Dev/selfhealing-code/selfheal-py-2/tests.py", line 62, in test_organize_table_data
    parsed_data = parse_yaml_data(self.yaml_data)
                  ^^^^^^^^^^^^^^^
NameError: name 'parse_yaml_data' is not defined

======================================================================
ERROR: test_parse_yaml_data (tests.TestOutput.test_parse_yaml_data)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dft/Dev/selfhealing-code/selfheal-py-2/tests.py", line 47, in test_parse_yaml_data
    parsed_data = parse_yaml_data(self.yaml_data)
                  ^^^^^^^^^^^^^^^
NameError: name 'parse_yaml_data' is not defined

----------------------------------------------------------------------
Ran 4 tests in 0.000s

FAILED (errors=4)
